name = "cloudflare-lighthouseci"
main = "src/index.js"
node_compat = true
compatibility_date = "2023-02-20"

[[ d1_databases ]]
binding = "<BINDING_NAME>"
database_name = "<DATABASE_NAME>"
database_id = "<UUID>"
